# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EarthQuakeAPI' do
	pod 'SwiftyJSON', '~> 4.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EarthQuakeAPI

  target 'EarthQuakeAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
